### ISSUE TITLE
vJoy Axis Touch Display button use the wrong button ID

### ISSUE THREAD

**Issue by FabXxXxXx** [bastianh/streamdeck-vjoy-w4rl0ck#4]
Hi,

On a dial, when affecting a button ID to the touch display, it's the dial's button ID which is used, and press indefinitily and no 100ms as inttended.

(Thank you for your amazing job, this plugin is top ! :) )

![Bug streamdeck-vjoy](https://github.com/bastianh/streamdeck-vjoy-w4rl0ck/assets/168359978/1d16f332-ef3e-426b-8863-6d730e844c1d)

**Comment by bastianh** [comment]
Thanks for the report. It should be fixed in version 0.2.1 which is currently building.

**Comment by FabXxXxXx** [comment]
That was quick ! Thank you. I've just tested the last version. Now the dial button and the touch button use their repectively button ID, that's working. 
But, I'm not sure about how the touch button works. It's written "The button is pressed for 100 ms". But it feels to me that I have to press it for 100 ms before it's trigger the action, and the press on the Vjoy's button ID seem to be very short. Far shorter than the press from the dial button. 
Is it what's intended ?

**Comment by FabXxXxXx** [comment]
Ah ok, I understand. I don't want to abuse your time, but if you would try to add a checkbox to be able to try the "hold" on touchTap, maybe it could make its use more predictable.
Another idea : are you able to make the screen "flash" when the Vjoy button is really trigger by the touchTap ? Just having this feedback could be enough.

**Comment by bastianh** [comment]
I did a small test and there is a function to show a success icon in a button for a short time, but it does not work for the display. I'll keep it in mind, but it might take some time until I can implement something.
